### ISSUE TITLE
Running our of memory

### ISSUE THREAD

**Issue by amanattrish** [tensorlayer/srgan#161]
I am running it on google colab and I have been assigned to TESLA K80 GPU
![GPU_name](https://user-images.githubusercontent.com/53205776/61869916-6b7e3100-aefa-11e9-8062-e2a12a5bf654.PNG)

Even 12GB ram is not suffice. I wonder if someone else is facing same problem!
![GPU_problem](https://user-images.githubusercontent.com/53205776/61870038-b304bd00-aefa-11e9-92e0-cd20086da923.PNG)

Consequently the popped out error is:
**2019-07-25 11:02:16.370912: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 28311552 exceeds 10% of system memory.
Traceback (most recent call last):
  File "train.py", line 357, in <module>
    train()
  File "train.py", line 100, in train
    grad = tape.gradient(mse_loss, G.weights)
AttributeError: 'Model' object has no attribute 'weights'**

### note: 
Pre-trained model vgg19.npy is in "srgan/models" directory.

**Comment by ChrisWu1997** [comment]
Hi, @amanattrish, regard the error, try to change `G.weights` to `G.trainable_weights` as there is some api changes in the latest tensorlayer.

@zsdonghao It seems that SRGAN should be updated.

**Comment by tuchuants** [comment]
I have met the same problem today when I try to use the latest version of tensorflow and tensorlayer to train the model. It always popped out warnning"Allocation of 33554432 exceeds 10% of system memory", but the training process could still on.

**Comment by iamAA** [comment]
This time everything worked fine except the process aborted with "^C" sign.
(see bottom of below attached pic)
![GPU_problem2](https://user-images.githubusercontent.com/34160895/61882364-03d5df00-af16-11e9-9f35-fa2094043bfd.PNG)

I guess it is because of running out of memory! Could you please some way to save memory?
![GPU_problem1](https://user-images.githubusercontent.com/34160895/61882420-25cf6180-af16-11e9-8643-9a42b4523f43.PNG)


**Sometimes the process aborted with "^C" sign without showing any other problem**

**Comment by zsdonghao** [comment]
I reduce the prefetch buffer size to 2. If it still out of memory, may need to reduce the batch size ..

**Comment by amanattrish** [comment]
I changed prefetch buffer size to 512 and batch size to 4. It worked for me.
Thank You! 👍

**Comment by amanattrish** [comment]
@zsdonghao 
could you please explain the prefetch buffer size?

**Comment by zsdonghao** [comment]
@amanattrish google : TensorFlow prefetch buffer   should help
