### ISSUE TITLE
_pickle.UnpicklingError: Failed to interpret file 'model\\vgg19.npy' as a pickle

### ISSUE THREAD

**Issue by Kvaibhav1997** [tensorlayer/srgan#247]
I am getting unpickling error while working with SRGAN network.
![Screenshot (14)](https://user-images.githubusercontent.com/68963976/177962998-57841dea-87d2-4f2e-a378-68dbeff98993.png)

_pickle.UnpicklingError: Failed to interpret file 'model\\vgg19.npy' as a pickle

**Comment by hanjr92** [comment]
![erroe](https://user-images.githubusercontent.com/73918561/178086983-93aa0879-1ea8-4b84-af5d-8e4eae47b32a.PNG)
please change LF to CRLF

**Comment by husterwang** [comment]
I have the same problem and the solution doesn't work for me. @hanjr92

**Comment by hanjr92** [comment]
please list you environments： windows or ubuntu, python version ,.....
I have test on (1. window 10 , pycharm , python 3.7; 2. ubuntu 20, python 3.7). 
Maybe the vgg19.npy was not downloaded correctly.
I will upload a copy to google drive. @husterwang

**Comment by husterwang** [comment]
Yes, the problem is that the vgg19.npy was not downloaded correctly. Thanks a lot.
Sorry to interrupt you. Another question: how to take my own low-resolution images as input? What could we modify the code?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tensorlayer/srgan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月27日(星期三) 下午5:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tensorlayer/srgan] _pickle.UnpicklingError: Failed to interpret file 'model\\vgg19.npy' as a pickle (Issue #247)





 
please list you environments： windows or ubuntu, python version ,.....
 I have test on (1. window 10 , pycharm , python 3.7; 2. ubuntu 20, python 3.7).
 Maybe the vgg19.npy was not downloaded correctly.
 I will upload a copy to google drive. @husterwang
